#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source ${OPENSHIFT_PYTHON_DIR}virtenv/bin/activate
 
export PYTHON_EGG_CACHE=${OPENSHIFT_PYTHON_DIR}virtenv/lib/python-2.6/site-packages

DJANGO_SETTINGS=settings_openshift

cd ${OPENSHIFT_REPO_DIR}
pip install -r ${OPENSHIFT_REPO_DIR}requirements.openshift.txt --log /tmp/pip.log --build /tmp/build

echo "Executing 'python ${OPENSHIFT_REPO_DIR}./manage.py syncdb --noinput'"
python "$OPENSHIFT_REPO_DIR"./manage.py syncdb --noinput --settings=$DJANGO_SETTINGS

echo "Executing 'python ${OPENSHIFT_REPO_DIR}./manage.py make_admin'"
python "$OPENSHIFT_REPO_DIR"./manage.py make_admin --settings=$DJANGO_SETTINGS

#echo "Executing 'python ${OPENSHIFT_REPO_DIR}./manage.py migrate'"
#python "$OPENSHIFT_REPO_DIR"./manage.py migrate --settings=$DJANGO_SETTINGS

echo "Executing 'python ${OPENSHIFT_REPO_DIR}./manage.py collectstatic --noinput -v0'"
python "$OPENSHIFT_REPO_DIR"./manage.py collectstatic --noinput -v0 --settings=$DJANGO_SETTINGS
